In [1]:
import pandas as pd
import numpy as np

In [2]:
# Conacatinating csv file of each subject

df = pd.concat(
    map(pd.read_csv, 
        [r'C:\Users\batra\INMAS\Sub_2.1.csv',
         r'C:\Users\batra\INMAS\Sub_2.2.csv',
         r'C:\Users\batra\INMAS\Sub_2.3.csv',
         r'C:\Users\batra\INMAS\Sub_2.4.csv',
         r'C:\Users\batra\INMAS\Sub_2.5.csv',
         r'C:\Users\batra\INMAS\Sub_2.6.csv',
         r'C:\Users\batra\INMAS\Sub_2.7.csv',
         r'C:\Users\batra\INMAS\Sub_2.8.csv',
         r'C:\Users\batra\INMAS\Sub_2.9.csv',
         r'C:\Users\batra\INMAS\Sub_2.10.csv',
         r'C:\Users\batra\INMAS\Sub_2.11.csv',
         r'C:\Users\batra\INMAS\Sub_2.12.csv',
         r'C:\Users\batra\INMAS\Sub_2.13.csv',
         r'C:\Users\batra\INMAS\Sub_14_1.csv',
          r'C:\Users\batra\INMAS\Sub_15_1.csv',
          r'C:\Users\batra\INMAS\Sub_16_1.csv',
          r'C:\Users\batra\INMAS\Sub_17_1.csv',
          r'C:\Users\batra\INMAS\Sub_18_1.csv',
          r'C:\Users\batra\INMAS\Sub_19_1.csv',
          r'C:\Users\batra\INMAS\Sub_20_1.csv',
          r'C:\Users\batra\INMAS\Sub_21_1.csv',
          r'C:\Users\batra\INMAS\Sub_22_1.csv',
          r'C:\Users\batra\INMAS\Sub_23_1.csv',
          r'C:\Users\batra\INMAS\Sub_24_1.csv',
          r'C:\Users\batra\INMAS\Sub_25_1.csv',
          r'C:\Users\batra\INMAS\Sub_26_1.csv',
        ]))

In [3]:
df.shape

(4671, 254)

In [4]:
2340/13

180.0

In [5]:
x=np.array(df.values)

In [6]:
x.shape

(4671, 254)

In [7]:
np.count_nonzero(np.isnan(x))

1972

In [8]:
x=np.nan_to_num(x)

In [9]:
np.count_nonzero(np.isnan(x))

0

In [10]:
x=np.array(x)

In [11]:
y=x[:,253]
print(y)

[3. 3. 3. ... 2. 2. 2.]


In [12]:
y[y == 1.].shape

(0,)

In [13]:
x=x[:,1:253]

In [14]:
from sklearn import preprocessing

In [15]:
standard_scaler_object = preprocessing.StandardScaler()

In [16]:
standard_scaler_object.fit(x)
x=standard_scaler_object.transform(x)

In [17]:
x.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,random_state=42)
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(3503, 252) (3503,)
(1168, 252) (1168,)


In [19]:
from sklearn import metrics

In [20]:
#1 random forest
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=10000, n_jobs=-1, random_state = 42)

In [21]:
# Train the classifier
clf.fit(x_train, y_train)

RandomForestClassifier(n_estimators=10000, n_jobs=-1, random_state=42)

In [22]:
y_test_pred=clf.predict(x_test)

In [23]:
clf.score(x_test, y_test)

0.877568493150685

In [24]:
metrics.accuracy_score(y_test,y_test_pred, normalize = True, sample_weight = None)

0.877568493150685

In [25]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_test_pred)

array([[701,  15,   8],
       [ 32, 165,  19],
       [ 33,  36, 159]], dtype=int64)

In [26]:
#2 Decision Tree
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)

DecisionTreeClassifier()

In [27]:
y_test_pred=clf.predict(x_test)

In [28]:
clf.score(x_test,y_test)

0.7611301369863014

In [29]:
metrics.accuracy_score(y_test,y_test_pred, normalize = True, sample_weight = None)

0.7611301369863014

In [30]:
#3 KNN
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 6)
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=6)

In [31]:
model.fit(x_train, y_train)
y_test_pred = model.predict(x_test)
metrics.accuracy_score(y_test, y_test_pred, normalize=True, sample_weight=None)

0.740582191780822

In [32]:
#4 SVM
from sklearn import datasets, svm
def evaluate_on_test_data(model=None):
    predictions = model.predict(x_test)
    correct_classifications = 0
    for i in range(len(y_test)):
        if predictions[i] == y_test[i]:
            correct_classifications += 1
    accuracy = 100*correct_classifications/len(y_test) #Accuracy as a percentage
    return accuracy

kernels = ('rbf','linear','poly')
accuracies = []
for index, kernel in enumerate(kernels):
    model = svm.SVC(kernel=kernel)
    model.fit(x_train, y_train)
    acc = evaluate_on_test_data(model)
    accuracies.append(acc)
    print("Accuracy with {} kernel = {}".format(kernel,acc))

Accuracy with rbf kernel = 70.29109589041096
Accuracy with linear kernel = 73.45890410958904
Accuracy with poly kernel = 63.613013698630134


In [33]:
#5 MLP
from sklearn.neural_network import MLPClassifier
model = MLPClassifier(hidden_layer_sizes=(25,), random_state=1)
model.fit(x_train, y_train)

D:\Users\batra\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(25,), random_state=1)

In [34]:
model.fit(x_train, y_train)
y_test_pred = model.predict(x_test)
metrics.accuracy_score(y_test, y_test_pred, normalize=True, sample_weight=None)

D:\Users\batra\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


0.800513698630137

In [35]:
#6 LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
model = LinearDiscriminantAnalysis(solver='lsqr', shrinkage=None) #shrinkage='auto'
model.fit(x_train, y_train)

LinearDiscriminantAnalysis(solver='lsqr')

In [36]:
model.fit(x_train, y_train)
y_test_pred = model.predict(x_test)
metrics.accuracy_score(y_test, y_test_pred, normalize=True, sample_weight=None)

0.7191780821917808

In [39]:
#7 Logistic Regression
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(max_iter = 500)
clf.fit(x_train, y_train)

LogisticRegression(max_iter=500)

In [40]:
y_test_pred=clf.predict(x_test)
metrics.accuracy_score(y_test, y_test_pred, normalize=True, sample_weight=None)

0.7371575342465754